# Generated by Django 4.2.1 on 2023-05-26 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('freq', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
