# Generated by Django 4.2.1 on 2023-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='freq',
            field=models.CharField(default='0d', max_length=100),
        ),
    ]
