# Generated by Django 4.2.1 on 2023-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_description_alter_task_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
